apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.4/manifests/install.yaml
configMapGenerator:
  - behavior: merge
    name: argocd-cm
    literals:
      - kustomize.buildOptions=--enable-helm --load-restrictor LoadRestrictionsNone
secretGenerator:
  - behavior: merge
    name: argocd-secret
    literals:
      # Default password is "admin"
      - admin.password=$2a$10$yakx1OJBonkB9kzYl/oU7OzycxVRdNyKV1WheR0ukSUqQMXc2S2nS
