apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.1/manifests/install.yaml
labels:
  - pairs:
      app.kubernetes.io/instance: argo-cd
configMapGenerator:
  - behavior: merge
    name: argocd-cm
    literals:
      - kustomize.buildOptions=--enable-helm --load-restrictor LoadRestrictionsNone
patchesStrategicMerge:
  - cluster-role-bindings-patch.yaml