apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.6.0/manifests/install.yaml
labels:
  - pairs:
      app.kubernetes.io/instance: argo-cd
configMapGenerator:
  - behavior: merge
    name: argocd-cm
    literals:
      - kustomize.buildOptions=--enable-helm --load-restrictor LoadRestrictionsNone