apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/thecooldrop/argocd-examples
    targetRevision: HEAD
    path: 'apps/external-secrets-operator/envs/integration'
    helm:
      valueFiles:
        - ../../base/values.yaml
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true