apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../base
secretGenerator:
  - behavior: merge
    name: argocd-secret
    literals:
      - admin.password=$2a$10$JyfQRnwP8O7aQ01ZpeMO..gw.FQqYReUGWuDXorcHeWWLvG49DT7m
