apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-integration-ingress
spec:
  rules:
    - host: argo-integration
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
