apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-integration-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: '/integration'
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
