apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-rocket-integration
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: patchClusterRoleBindings.yaml
configMapGenerator:
  - behavior: merge
    name: argocd-cmd-params-cm
    literals:
      - server.insecure=true
      - server.rootpath=/integration
      - server.basehref=/integration/
