apiVersion: builtin
kind: PrefixSuffixTransformer
metadata:
  name: addIntegrationSuffixs
suffix: -integration
fieldSpecs:
  - path: metadata/name
    group: rbac.authorization.k8s.io
    apiVersion: v1
    kind: ClusterRole
  - path: metadata/name
    group: rbac.authorization.k8s.io
    apiVersion: v1
    kind: ClusterRoleBinding
