apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
spec:
  generators:
    - git:
        repoURL: https://github.com/thecooldrop/argo-examples.git
        revision: HEAD
        files:
          - path: examples/single-cluster/apps/*/envs/integration/config.yaml
  template:
    metadata:
      name: '{{ path[3] }}-integration'
    spec:
      source:
        repoURL: https://github.com/thecooldrop/argo-examples.git
        targetRevision: HEAD
        path: '{{path}}'
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd-rocket-integration
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
