apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
spec:
  generators:
    - git:
        repoURL: https://github.com/thecooldrop/argo-examples.git
        revision: HEAD
        files:
          - path: examples/single-cluster/apps/*/envs/integration/config.yaml
  template:
    metadata:
      name: '{{ path[3] }}-integration'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd-rocket-integration
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
  templatePatch: |
    {{- if (eq .type "kustomize") }}
      source:
        repoURL: https://github.com/thecooldrop/argo-examples.git
        targetRevision: HEAD
        path: '{{path}}'
    {{- else if (eq .type "helm") }}
      sources:
      - chart: {{ .chart }}
        repoUrl: {{ .repo }}
        targetRevision: {{ .version }}
        valueFiles:
        {{- range .valueFiles }}
        - $values/{{ . }}
        {{- end }}
      - repoUrl: https://github.com/thecooldrop/argo-examples.git
        path: {{ path }}
        targetRevision: HEAD
        ref: values
    {{- end}}
