apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-production-ingress
spec:
  ingressClassName: nginx-production
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: '/production'
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
