apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  template:
    spec:
      containers:
        - args:
            - /nginx-ingress-controller
            - --election-id=$ELECTION_ID
            - --controller-class=$CONTROLLER_CLASS
            - --ingress-class=$INGRESS_CLASS
            - --configmap=$(POD_NAMESPACE)/ingress-nginx-controller
            - --validating-webhook=:8443
            - --validating-webhook-certificate=/usr/local/certificates/cert
            - --validating-webhook-key=/usr/local/certificates/key
            - --watch-ingress-without-class=true
            - --enable-metrics=false
            - --publish-status-address=localhost
          name: controller
          envFrom:
            - configMapRef:
                name: nginx-controller-args
