type: helm
chart: ingress-nginx
repo: https://kubernetes.github.io/ingress-nginx
namespace: nginx-rocket-integration
version: 4.10.0
releaseName: ingress-integration
valueFiles:
  - '../../base/values.yaml'
  - 'values.yaml'
