apiVersion: builtin
kind: NamespaceTransformer
metadata:
  name: setNamespaceName
  namespace: nginx-rocket-production
setRoleBindingSubjects: allServiceAccounts
fieldSpecs:
  - path: metadata/namespace
